### ISSUE TITLE
package manager weirdness

### ISSUE THREAD

**Issue by krugazor** [kylef/Stencil#101]
the swift package manager identifies its dependencies with the url

including both Commander and Stencil as dependencies result in Spectre being listed with and without the ".git", and therefore produces the error:

error: rename error: Directory not empty (66): /private/tmp/Test/Packages/Spectre -> /private/tmp/Test/Packages/Spectre-0.7.2

as "both" dependencies want the same directory name

**Comment by kylef** [comment]
This should be fixed in [Stencil 0.8.0](https://github.com/kylef/Stencil/releases/tag/0.8.0).
