### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by adongarwar** [kylef/Stencil#104]
I followed the steps mentioned at https://fuller.li/posts/using-swift-package-manager-with-carthage
When i include the framework in my iOS project, i get the following compliation error.
<img width="478" alt="screen shot 2017-03-04 at 2 31 35 pm" src="https://cloud.githubusercontent.com/assets/4019449/23582806/f524bafa-00e7-11e7-8471-dd475bfd54a6.png">

Below are the logs that igot while doing carthage build. Can you please help with this?
![screen shot 2017-03-04 at 2 39 17 pm](https://cloud.githubusercontent.com/assets/4019449/23582872/84b30d74-00e9-11e7-8671-e36b4232cd36.png)

**Comment by kylef** [comment]
As mentioned in our [installation instructions](https://stencil.fuller.li/en/latest/installation.html#carthage) we do not offer any support for Carthage use, it's use at your own risk. I'd recommend using one of the supported/recommended manages in our documentation.

> Use at your own risk. We don’t offer support for Carthage and instead recommend you use Swift Package Manager.
