### ISSUE TITLE
Ability to keep empty lines in output

### ISSUE THREAD

**Issue by artyom-razinov** [kylef/Stencil#105]
I'm using Sourcery for code generation, which uses Stencil, and I want to have empty lines in output, but all empty lines are removed from output. Is there a way to insert an empty line? Like some tag "{% emptyLine %}". Or maybe it can be somehow controlled so I have to improve Sourcery.

**Comment by artyom-razinov** [comment]
Note: I solved this issue using "sed" in my script. I write "/*emptyLine*/" in templates and remove it using sed. But it is a kind of a kludge.

**Comment by kylef** [comment]
You can just enter an empty line `\n\n` there is no need for a special template tag for this.
