### ISSUE TITLE
Is there a way to loop a single value

### ISSUE THREAD

**Issue by samskiter** [kylef/Stencil#113]
I'm using Sourcery and annotations are returned as an array if there are many or as a single value if there is just one. (see: https://github.com/krzysztofzablocki/Sourcery/blob/4e920792664029203820fba1a63ba4ba925f552e/SourceryTests/Parsing/AnnotationsParserSpec.swift)

Is there any way from a template to either 'loop' over a single value or declare an array containing just my single value that I could then loop over?

**Comment by kylef** [comment]
Looks like this was solved in https://github.com/SwiftGen/StencilSwiftKit/issues/44
