### ISSUE TITLE
enhancement - zero Based Counter  {{forloop.counter}}   ->  {{forloop.zeroBasedCounter}}  

### ISSUE THREAD

**Issue by wwe-johndpope** [kylef/Stencil#121]
seems like  there's some headache implementing this. Perhaps we can simply create a new method to extend this functionality?

https://github.com/ainame/Swiftkiq/blob/2bc89abc7befa87de585ffbac4d29e428919ef86/Templates/Router.stencil

**Comment by kylef** [comment]
Added in https://github.com/kylef/Stencil/commit/7b9817ed50b83ad874a6885f939fc1c77ab92193
