### ISSUE TITLE
Custom Template Tags and Filters documentation typo

### ISSUE THREAD

**Issue by Antondomashnev** [kylef/Stencil#127]
In the attached screenshot the parameter to multiply by should be `amount` not 2.  
<img src="https://monosnap.com/file/MV17aGG68ydTfpyfKuKdcwMAcnixB8.png" width=320>

  
@kylef is there a way to create a PR to the [http://stencil.fuller.li/](http://stencil.fuller.li/)?

**Comment by kylef** [comment]
Thats a good point, it is indeed incorrect.

Yes, the website source is inside the `docs` directory. Source for that file can be found at https://github.com/kylef/Stencil/blob/master/docs/custom-template-tags-and-filters.rst .

**Comment by Antondomashnev** [comment]
@kylef thanks, will submit a PR for it.

**Comment by paulmelnikow** [comment]
Hey @Antondomashnev, just a heads up that you should open the PR on this repo instead of on your fork.

**Comment by Antondomashnev** [comment]
Haha, nice catch, thanks @paulmelnikow
