### ISSUE TITLE
Literal '%' in template

### ISSUE THREAD

**Issue by paulmelnikow** [kylef/Stencil#137]
Hi, thanks for the great library!

I'm using Stencil to generate an HTML page with an embedded style sheet.

My template has lines like this:

```html
<style>
    table {
        font-size: 140%;
    }
</style>
```

When Stencil renders this template, it drops the `%`:

```html
<style>
    table {
        font-size: 140;
    }
</style>
```

Is this a bug? Is there a way to work around it?

**Comment by kylef** [comment]
This is certainly a bug, we should fix it!

**Comment by kylef** [comment]
I'll try cleanup this with #136 and #135 and make a patch release.

**Comment by paulmelnikow** [comment]
Woot! Thanks for the fast response!

**Comment by kylef** [comment]
@paulmelnikow I'm actually not able to reproduce this. Could you please share a bit more information:

- Swift Version
- Stencil version
- Any extensions or tools used in conjunction with Stencil

**Comment by paulmelnikow** [comment]
Just saw this. Surprised! Though yes, I will give it a shot and see.

**Comment by paulmelnikow** [comment]
I haven't had time to get back to this, though I suspect the problem was an `NSLog` that should have been `print`.
