### ISSUE TITLE
Can't use initializer for Context because of internal protection level

### ISSUE THREAD

**Issue by ahoang** [kylef/Stencil#138]
We are in the process of converting to Swift 3 (then later Swift 4) syntax and we upgraded Stencil from `0.5.x` to `0.8.0`.

After upgrading, I'm receiving an error when trying to initialize an instance of Context, stating we can't use the initializer because of internal protection level.

**Comment by kylef** [comment]
@ahoang That is correct, please see the release notes / changelog for 0.8 https://github.com/kylef/Stencil/releases/tag/0.8.0


>### Breaking
>- It is no longer possible to create `Context` objects. Instead, you can pass a
>  dictionary directly to a `Template`s `render` method.
>
>  ``` diff
>  - try template.render(Context(dictionary: ["name": "Kyle"]))
>  + try template.render(["name": "Kyle"])
>  ```
