### ISSUE TITLE
Support {% if item in list %}

### ISSUE THREAD

**Issue by kdawgwilk** [kylef/Stencil#142]
I have been wishing I could do something list the following in Stencil templates

```
{% if item in list%}
// Do stuff here now that we know this is in the list
{% endif %}
```

**Comment by kdawgwilk** [comment]
I initially brought this up over in Sourcery krzysztofzablocki/Sourcery#415

**Comment by AliSoftware** [comment]
Couldn't you just do `{% if list|contains:item %}`? Or does that contains filter not work with arrays but only strings?

**Comment by kdawgwilk** [comment]
I have not tried this but I will give it a go

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ilyapuchka** [comment]
@AliSoftware @kdawgwilk according to StencilSwiftKit code it looks like it is indeed defined only on strings
