### ISSUE TITLE
Error when I compile the app

### ISSUE THREAD

**Issue by Rubenfer** [kylef/Stencil#195]
I'm using Stencil on my App but when I try to compile it I have this error:

Command /bin/sh failed with exit code 1

A shell task (/usr/bin/xcrun codesign --force --sign - --preserve-metadata=identifier,entitlements /Users/rubenfernandez/Library/Developer/Xcode/DerivedData/APP_NAME/Build/Products/Debug-iphonesimulator/APP_NAME.app/Frameworks/Stencil.framework) failed with exit code 1:
/Users/rubenfernandez/Library/Developer/Xcode/DerivedData/APP_NAME/Build/Products/Debug-iphonesimulator/APP_NAME.app/Frameworks/Stencil.framework: replacing existing signature

/Users/rubenfernandez/Library/Developer/Xcode/DerivedData/APP_NAME/Build/Products/Debug-iphonesimulator/APP_NAME.app/Frameworks/Stencil.framework: resource fork, Finder information, or similar detritus not allowed

How can I solve it?
Thanks in advance

**Comment by wukerplank** [comment]
@Rubenfer Does not seem to be a Stencil issue: https://developer.apple.com/library/content/qa/qa1940/_index.html
