### ISSUE TITLE
New tag required for Swift 4.1 compatibility

### ISSUE THREAD

**Issue by djones6** [kylef/Stencil#206]
#184 updated the version of PathKit to `0.9`, but this change has not yet been tagged.  The latest Stencil tag (`0.10.1`) still uses PathKit `0.8`.

This is required for Swift 4.1 compatibility, to pick up kylef/PathKit#48 which was tagged in `0.9.1`.

**Comment by kylef** [comment]
https://github.com/kylef/Stencil/releases/tag/0.11.0 is tagged
