### ISSUE TITLE
Example Project

### ISSUE THREAD

**Issue by BryanJBryce** [kylef/Stencil#39]
As someone who is not familiar with Django or web development in general, I'm trying to wrap my head around how/where I would use this. An example project would be very illustrative.

**Comment by kylef** [comment]
Stencil can be used for various reasons. Here's some uses of Stencil in the wild:

- [QueryKit CLI](https://github.com/QueryKit/querykit-cli) - Code generation
- [SwiftGen](https://github.com/AliSoftware/SwiftGen) - Code generation

It may be used for things like the following:

- Website HTML generation ([example](https://github.com/kylef/fuller.li/blob/master/theme/templates/speaking.html))
- Code generation
- Text Templates (for example, to substitute names/content in content being shown to the user)
- Email templates (for example, to substitute names/content in emails being sent out)
