### ISSUE TITLE
Scanner Causes Memory Leak

### ISSUE THREAD

**Issue by thedillonb** [kylef/Stencil#49]
Using the following code:

```swift
    func loadMarkdown(data: String) {
        do {
            let context = Context(dictionary: ["data": data])
            let template = try Template(named: "markdown.stencil")
            let rendered = try template.render(context)
            print(rendered)
        } catch {
            print("Readme error \(error)")
        }
    }
```

It looks like the Scanner object is leaking memory:

![image](https://cloud.githubusercontent.com/assets/1644068/12029608/01c9a22c-adbd-11e5-87f7-d27736574b73.png)

If I run the code again, it leaks 2x the memory so it's not just static resources that are being allocated on the first run - they're being created every time.

**Comment by kylef** [comment]
That almost certainly seems like a Swift bug, which version of Swift are you using?

**Comment by thedillonb** [comment]
Apple Swift version 2.1.1 (swiftlang-700.1.101.15 clang-700.1.81)
Target: x86_64-apple-darwin15.0.0

**Comment by kylef** [comment]
@thedillonb Would you be able to share your template `markdown.stencil` so I can reproduce this?
