### ISSUE TITLE
Comparison operators

### ISSUE THREAD

**Issue by NastyAlloys** [kylef/Stencil#52]
Can I use some comparison operators like in Django template?

**Comment by kylef** [comment]
You can't at the moment, but I'm open to implementing this. Do you have any specific examples?

**Comment by vinbhai4u** [comment]
currently only string, but it good if we get Integer.

Thanks and btw great lib :)

**Comment by dileping** [comment]
@kylef, considering Swift is type safe, how about trying to cast values to `Equitable` and then compare? If values can not be cast to `Equitable`, just return `false`.

**Comment by kylef** [comment]
@dileping I'm thinking more in terms of first having to convert the RHS literal to a matching type (Int, UInt, Int8, UInt8, Double, Float, String, etc)

```html+django
{% if user.age > 21 %}
{% if user.age > 21.0 %}
{% if user.username != "kyle" %}
{% if user.balance == 21.99 %}
```

**Comment by kylef** [comment]
Regardless, you can't just covert them both to equatable, they have associated type requirements.

**Comment by dileping** [comment]
@kylef I think something like this should do the trick for you:

```swift
protocol AnyEquatable : Equatable {
}

extension AnyEquatable {
    func isEqual(any:Any) -> Bool {
        guard let any = any as? Self else {
            return false
        }
        
        return self == any
    }
}

extension String : AnyEquatable {
}

extension Int : AnyEquatable {
}
```

**Comment by califrench** [comment]
+1 comparison operators would make stencil way more useful. I'd love to be able to do things like 
```html+django
<li {% if currentPage == "home" %} class="active" {% endif %} >Home</li>
```

**Comment by itchingpixels** [comment]
also, it would be useful to have proper boolean checks! extremely useful in our case:).

**Comment by gizmoboy7** [comment]
Is the equality operator implemented? It doesn't seem to work

**Comment by divyenduz** [comment]
+1 For equality operator not working. Is that resolved ?

**Comment by simonstewart** [comment]
@divyenduz did you figure this out?
I'm wanting to use a simple comparison like: {% if enumName == "Something" %}

**Comment by divyenduz** [comment]
Nope, I was using this for a hobby project, moved my code to .swift file in place of template [https://github.com/divyenduz/mylifefootball.com](https://github.com/divyenduz/mylifefootball.com)

**Comment by simonstewart** [comment]
@kylef thanks!
