### ISSUE TITLE
SPM error: NoSources

### ISSUE THREAD

**Issue by sauliusgrigaitis** [kylef/Stencil#53]
Testing feature came with latest DEVELOPMENT-SNAPSHOT-2016-02-25-a release and it can't build (same issue reported in PathKit).

**Comment by kylef** [comment]
Depends on https://github.com/apple/swift-package-manager/pull/152 to be merged/released.

**Comment by czechboy0** [comment]
@kylef Even though it's not ideal, I think this swiftpm snapshot will be the most current one for a couple of weeks. You might consider releasing one version where the Tests folder is renamed for the time being. And then rename it back once swiftpm has a newer snapshot where this is fixed. This is what I did with Jay - takes 30 seconds and will help many who are trying to integrate your projects.
