### ISSUE TITLE
if condition

### ISSUE THREAD

**Issue by vinbhai4u** [kylef/Stencil#56]
Is it possible to give

{% if (I.NO == 1) %}

if to check in for loop??

**Comment by kylef** [comment]
You can check for the first and last items like this:

```html+django
{% for user in users %}
  {% if forloop.first %}
    This is the first user.
  {% endif %}
{% endfor %}
```

```html+django
{% for user in users %}
  {% if forloop.last %}
    This is the last user.
  {% endif %}
{% endfor %}
```

```html+django
{% for user in users %}
  This is user number {{ forloop.counter }} user.
{% endfor %}
```

Does this do what you want?

**Comment by vinbhai4u** [comment]
no, I was looking more like 

```
if I.AttachmentType == "type1" {
   //div for type 1
}
else if I.AttachmentType == "type2" {
   //div for type 2
}
else{
   // default type which never occurs 
}
```

**Comment by kylef** [comment]
Currently that's not possible, however we're discussing adding comparison operators to #52. Currently I'm a little worried about how this will work because Swift is type safe.

You are looking to do equality comparison against strings, or other types too?

**Comment by kylef** [comment]
Going to close this and move to https://github.com/kylef/Stencil/issues/52.

**Comment by gizmoboy7** [comment]
Hi @kylef 
I'm looking for an equality comparison, either string or int, have an use case in a for loop. Is the equality check on the roadmap?
