### ISSUE TITLE
Support Complex Inheritance

### ISSUE THREAD

**Issue by shnhrrsn** [kylef/Stencil#60]
Inheritance only appears to work once, as soon as you extend twice it no longer inherits blocks from the root template.

Example:

`master.stencil`

``` twig
<!DOCTYPE html>
<html>
    <body>
        <div class="content">
            {% block content %}{% endblock %}
        </div>
    </body>
</html>
```

`app.stencil`

``` twig
{% extends "master.stencil" %}
```

`welcome.stencil`

``` twig
{% extends "app.stencil" %}

{% block content %}
    Testing
{% endblock %}
```

When `welcome.stencil` is rendered, the HTML from `master.stencil` is rendered, but the `content` block overridden in `welcome.stencil` is completely ignored.  Even if you redefine `{% block content %}{% endblock %}` in `app.stencil` it still gets ignored.

In addition to this, there should also be a way to render the contents of the parent block you’re overriding, so if we change the above templates:

`app.stencil`

``` twig
{% extends "master.stencil" %}

{% block content %}Hello{% endblock %}
```

`welcome.stencil`

``` twig
{% extends "app.stencil" %}

{% block content %}{{ parent() }} World{% endblock %}
```

The `content` block should render as "Hello World".

I'm unfamiliar with Django/Jinja, but Twig (which is based on those) supports both of these and an example can be found here: http://twigfiddle.com/box9s8

**Comment by kylef** [comment]
Inheritance in Django/Jinja does certainly work multiple times, and I think it should in Stencil. This is a bug that it doesn't work. Will try taking a look over the weekend.

**Comment by kylef** [comment]
@shnhrrsn I've added support for multiple-inheritance in 393dc88, I'll be adding support for rendering the super block shortly (`{{ block.super }}`).

**Comment by kylef** [comment]
@shnhrrsn https://github.com/kylef/Stencil/commit/d75db241ac2ceacc96d424196aa9a675a08a8752 adds support for using `{{ block.super }}` to render the parent block.
