### ISSUE TITLE
Memory leaks With html template

### ISSUE THREAD

**Issue by abuobaida** [kylef/Stencil#62]
When using stencil with a template from an html file leaks memory. The observed number of leaks and leaked memory size increase with the length of the html file. I attached a project to demonstrate the issue.
[TestLeaks.zip](https://github.com/kylef/Stencil/files/174720/TestLeaks.zip)

**Comment by mkBajaj** [comment]
Hi Team , Any update on this memory leak issue , in my app it is increasing 100MB in 1 shot .

**Comment by zhangbozhb** [comment]
@abuobaida @mkBajaj 
It did memory leak.  Scanner in  Lexer file leaks.
Method: Scanner.scan leaks. 
How fix:
use content.substringFromIndex(index) replace content[index..<content.endIndex]

Code follows:

// Method: func scan(until until: String, returnUntil: Bool = false) -> String {

    var index = content.startIndex
    while index != content.endIndex {
      let substring = content.substringFromIndex(index) //content[index..<content.endIndex]
      if substring.hasPrefix(until) {
        let result = content.substringToIndex(index) //content[content.startIndex..<index]
        content = substring

        if returnUntil {
          content = content.substringFromIndex(until.endIndex) //content[until.endIndex..<content.endIndex]
          return result + until
        }

        return result
      }

      index = index.successor()
     }


// Method: func scan(until until: [String]) -> (String, String)?

    var index = content.startIndex
    while index != content.endIndex {
      let substring = content.substringFromIndex(index) //content[index..<content.endIndex]
      for string in until {
        if substring.hasPrefix(string) {
          let result = content.substringToIndex(index) //content[content.startIndex..<index]
          content = substring
          return (string, result)
        }
      }

      index = index.successor()
    }

**Comment by kylef** [comment]
This was fixed by #68.

**Comment by mkBajaj** [comment]
Hi Kylef , 
Thanks for fixing this memory  issue this is really help full , but What We  observed is memory issue fix code change available in V0.6 which is swift 3.0, We are using previous version using V0.5.X ,which supports swift 2.3 so request you to move memory leak fix  change to this version as well.

Appreciate your support and time.
 .
