### ISSUE TITLE
Add support for swift snapshot swift-DEVELOPMENT-SNAPSHOT-2016-05-03

### ISSUE THREAD

**Issue by vadimeisenbergibm** [kylef/Stencil#66]

**Comment by vadimeisenbergibm** [comment]
The following fork compiles with swift-DEVELOPMENT-SNAPSHOT-2016-05-03: https://github.com/necolt/Stencil

**Comment by califrench** [comment]
The mentioned fork compiles with `swift-DEVELOPMENT-SNAPSHOT-2016-05-09` without warnings.

**Comment by kylef** [comment]
Swift 3.0 support has been added in [Stencil 0.6.0](https://github.com/kylef/Stencil/releases/tag/0.6.0).
