### ISSUE TITLE
Variables in for loops don't seem to be evaluated?

### ISSUE THREAD

**Issue by plivesey** [kylef/Stencil#70]
Trying to make this description short and to the point. Let me know if you need more info.

I have a custom filter:

```
static func keys(value: Any?) throws -> Any? {
        guard let dictionary = value as? [String: Any] else { throw FilterError.InvalidInputType }
        return Array(dictionary.keys)
    }
```

In my `.stencil` file:

```
{% for field in spec|keys %}
```

However, it seems like it assumes "spec|keys" is the name of my variable and doesn't try to evaluate it.

Is there something I'm missing here? Or is there a better way of doing this?

**Comment by plivesey** [comment]
Got it working with something like:

```
public class ForNode : NodeType {
  let variable:ExpressionType
  let loopVariable:String
  let nodes:[NodeType]
  let emptyNodes: [NodeType]

  enum ExpressionType {
    case variable(Variable)
    case filterExpression(FilterExpression)
  }
```
```
if variable.containsString("|") {
      if let filter = try? FilterExpression(token: variable, parser: parser) {
        self.variable = .filterExpression(filter)
      } else {
        // Hack to get around the try? for now
        self.variable = .variable(Variable(variable))
      }
    } else {
      self.variable = .variable(Variable(variable))
    }
```
```
public func render(context: Context) throws -> String {
    let values: Any?
    switch variable {
    case .variable(let variable):
      values = try variable.resolve(context)
    case .filterExpression(let expression):
      values = try expression.resolve(context)
    }
```

Not sure if this is the right way of doing it. But can pull request if you think something along these lines is right (fixing the hack).

**Comment by kylef** [comment]
@plivesey Yes I'd love a pull request. This is something that isn't yet supported.

I think this can be implemented a little simpler than the changes you have made. You don't need to add the complexity of detecting if it is a filter expression. `FilterExpression` internally will already handle if there are no filters. You can remove the use of `Variable` and only deal with `FilterExpression`.

This is similar to how VariableNode's are always constructed from a `FilterExpression`.

```swift
VariableNode(variable: try compileFilter(token.contents))
```

**Comment by plivesey** [comment]
Yeah, I was thinking of the same thing. I'll create a pull request at some point...probably not going to work on this for a while, but maybe I'll get the pull request done earlier.

Thanks.

**Comment by plivesey** [comment]
Btw, I think it's unlikely I'll submit this pull request any time soon. Turns out I didn't need this for my project and the project is taking longer than expected. So not much extra time...but hopefully one day, I'll get round to it.
