### ISSUE TITLE
Index out of bounds should throw

### ISSUE THREAD

**Issue by tkrajacic** [kylef/Stencil#72]
When a template contains an invalid index (e.g. `elements.1` where elements only has 1 element) Stencil crashes with a fatal error.

In my opinion it would be better to throw if the index is out of bounds as the template is a user-written document and the assumption that a subscript index is correct doesn't hold.

I had a look through the code but couldn't figure out right away where this happens.
For variables I found one instance where the index wasn't checked, but not for context lookup for arrays:

`current = array[index]`

**Comment by kylef** [comment]
I agree @tkrajacic, fixed in 1e3afc0dd548d2ba4a145329d6b6fb6534df44e7
