### ISSUE TITLE
is it possible to use stencil in vapor?

### ISSUE THREAD

**Issue by yudun1989** [kylef/Stencil#74]
as vapor is a swift server side framework, and stencil is a very powerful template engine, it will be good to intergrate vapor with stencil

**Comment by macavon** [comment]
I looked for the answer to this recently, and found some links to a `vapor-stencil` repo, but they were dead – leading to 404 error. I would guess that it has been abandoned in favour of their own Leaf templating language, but you could try asking on Slack, where the Vapor people seem to be quite active.

**Comment by kylef** [comment]
As shown in the README, you can render a template using Stencil as follows:

```swift
let context = Context(dictionary: [
  "articles": [
    [ "title": "Migrating from OCUnit to XCTest", "author": "Kyle Fuller" ],
    [ "title": "Memory Management with ARC", "author": "Kyle Fuller" ],
  ]
])

do {
  let template = try Template(named: "template.stencil")
  let rendered = try template.render(context)
  print(rendered)
} catch {
  print("Failed to render template \(error)")
}
```

You can do this in Vapor or whatever framework of your choice.
