### ISSUE TITLE
Documentation for template inheritance

### ISSUE THREAD

**Issue by macavon** [kylef/Stencil#75]
The `extends` and `block` tags are not described in the README. Is documentation waiting on a resolution of #60 or is its absence just an oversight? I can write something about them if it would help.

**Comment by kylef** [comment]
I've been wanting to create a proper documentation website, which I've kicked off in https://github.com/kylef/Stencil/commit/3293d8a526ca2aba5313db15ab96df6b78d6dd52 which you can view at https://stencil.rigidapp.com, will be adding template inheritance once I've finished #60.

**Comment by macavon** [comment]
That will be fine, then. Thanks.

**Comment by kylef** [comment]
You can find full documentation for template inheritance at https://stencil.fuller.li/en/latest/templates.html#template-inheritance
