### ISSUE TITLE
Use of undeclared type 'Float80'

### ISSUE THREAD

**Issue by crsantos** [kylef/Stencil#76]
From `0.7.0` to `0.7.1`/`0.7.2` an error triggered regarding `Float80`.

```bash
Pods/Stencil/Sources/Expression.swift:205:21: Use of undeclared type 'Float80'
```

Looks like:

```swift
override func compare(lhs: Float80, rhs: Float80) -> Bool
```

Isn't `Float80` an architecture dependent type?

**Comment by kylef** [comment]
Thanks for the report @crsantos. Could you please let me know which platform/architecture you are using. I wasn't aware this isn't always available.

I think we could determine the largest type available on the given platform and use that.

**Comment by kylef** [comment]
Made some changes in d3706f0, but I'd like to figure out how to find the largest available number and support this. Otherwise comparisons against other largest float types would be broken.

**Comment by crsantos** [comment]
Not on my computer right now but pretty sure that was running on an iPhone 6S.
On that day a quick Google search led me to this:
https://forums.developer.apple.com/thread/5026

Let me know if you need some more info when I reach home.
