### ISSUE TITLE
IfTag should support filters, same as ForTag does

### ISSUE THREAD

**Issue by krzysztofzablocki** [kylef/Stencil#90]
IfTag should support filters so we can do things like `{% if name|contains:"Bar" %}`

I wonder if there is a way we could just generally support filters in all nodes, instead of raw variables, thus avoiding having to add this at each node level?

**Comment by kylef** [comment]
I agree and something I've wanted to implement for 1.0. It's pretty simple to support filters in most cases.

Pretty much all you need to do is the following:

```swift
let filter = try parser.compileFilter(variable)
```

Then you have a `Resolvable` type that you can resolve just like variables.

This is one of the reasons that I deprecated supporting spaces in filters in the previous release as this would add a lot of complexity to knowing the difference between a filter and an if expression components in the parser, especially while keeping the two components separated in the code base. I don't want spaces to only be supported in some places as it leads to confusing behaviours for template authors based on the context.

**Comment by krzysztofzablocki** [comment]
Awesome, thanks! :)
