### ISSUE TITLE
Support templates compiled into Swift binaries

### ISSUE THREAD

**Issue by timburks** [kylef/Stencil#97]
I have an application where it seems better to compile my templates directly into the executable.

It was easy to provide that with a [custom Loader class](https://github.com/grpc/grpc-swift/blob/master/Plugin/Sources/protoc-gen-swiftgrpc/InternalLoader.swift). I chose to embed templates as [base64-encoded strings](https://github.com/grpc/grpc-swift/blob/master/Plugin/Sources/protoc-gen-swiftgrpc/templates.swift) that were created by a [small Swift tool](https://github.com/grpc/grpc-swift/blob/master/Plugin/Sources/TemplateEncoder/main.swift).

You might find it useful to include something like this in Stencil. Let me know if you'd like a pull request.

**Comment by kylef** [comment]
@timburks I think with Swift 4 getting multi-line template strings, we should implement a `MemoryLoader` or such:

```swift
let loader = MemoryLoader([
    "index.html": """
...
""",
    "base.html": """
...
""",
])
```

**Comment by kylef** [comment]
I've added a `DictionaryLoader` which works as above. Perhaps you can refactor your implementation to decode your Base64 into the DictionaryLoader. Then when you adopt Swift 4 you can use multi-line strings.
